# Generated by Django 4.2.4 on 2023-08-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('media_type', models.CharField(choices=[('vg', 'Videogioco'), ('f', 'Film'), ('tv', 'Serie TV'), ('a', 'Anime')], max_length=5)),
            ],
        ),
    ]
