# Generated by Django 4.2.4 on 2023-09-08 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapop', '0002_mediavote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediavote',
            name='vote',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
