# Generated by Django 4.2.5 on 2023-09-11 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapop', '0003_alter_mediavote_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediavote',
            name='vote',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
