# Generated by Django 4.2.4 on 2023-09-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_reviewcomment_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='opera',
            new_name='media',
        ),
    ]
