# Generated by Django 4.2.4 on 2023-09-08 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_opera_review_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
